# Generated by Django 5.0.6 on 2024-05-29 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=1000, null=True),
                ),
            ],
            options={
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_depense", models.DateTimeField(auto_now_add=True)),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, max_digits=1000, null=True),
                ),
                ("description", models.TextField(null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="depenses.categorie",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Depense",
                "verbose_name_plural": "Depenses",
            },
        ),
    ]
