# Generated by Django 5.0.6 on 2024-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_remove_fournisseur_enregistre_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="date_fourniture",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
