# Generated by Django 5.0.6 on 2024-06-05 01:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "actifs_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "passifs_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "capitaux_propres",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("Actif", "Actif"),
                            ("Passif", "Passif"),
                            ("Capitaux Propres", "Capitaux Propres"),
                        ],
                        max_length=50,
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentComptable.compte",
                    ),
                ),
            ],
        ),
    ]
